# Run as: python src/07_enumerate_emapunil_round3.py \
 # --r1_tsv templates_functional_groups/R1_round3.tsv \
 # --r2_tsv templates_functional_groups/R2_round3.tsv \
 # --out_sdf docking/emap_enum_round3/round3_max.sdf \
 # --out_smiles docking/emap_enum_round3/round3_max.csv \
 # --manifest docking/emap_enum_round3/round3_manifest.txt

# Created 11/28/25
import os, csv, argparse, hashlib, sys
from rdkit import Chem
from rdkit.Chem import AllChem

TEMPLATE = "CCN({R2})C(=O)Cn2c3c(cnc(n3)c4ccccc4)n(c2=O){R3}"

# loads tsv file for functional group R2 and R3 substitutions - loaded in the templates directory as R2_round3.tsv, R3_round3.tsv 
# primary modification in this round would be the silyl ether additions which are exploratory testing, OCHF3 groups (fluoroalkyl ethers) which are done to permute logD values
# Also, perfluoroalkyl groups (with longer side chains and phenyl groups) are being added to tweak MW and logD7.4 values systematically, and this is also the largest enum round
# total of 1782 analogs created in this round with 34 R2 substitutions and 60 R3 substitutions (originally 2040), removed failures and improbable bond types
def load_tsv(path):
    items=[]
    with open(path) as f:
        for ln in f:
            ln=ln.strip()
            if not ln or ln.startswith("#"): continue
            parts=ln.split("\t")
            if len(parts)<2:
                raise ValueError(f"Bad line in {path}: {ln}")
            tag, smi = parts[0].strip(), parts[1].strip()
            items.append((tag,smi))
    if not items:
        raise ValueError(f"No entries in {path}")
    # ensure unique tags
    tags=[t for t,_ in items]
    if len(tags)!=len(set(tags)):
        dup=[t for t in set(tags) if tags.count(t)>1]
        raise ValueError(f"Duplicate tags in {path}: {dup}")
    return items
# creates SHA-256 keys for each ligand ID which can be used for verification of CSVs.
def sha256(path):
    h=hashlib.sha256()
    with open(path,'rb') as f:
        for chunk in iter(lambda: f.read(1<<20), b''):
            h.update(chunk)
    return h.hexdigest()

# main function that enumerates the ligands by functional group - R2 and R3 lists are functional group substitutions that are combined and permuted with one another
# permutations are generated by replacing the R2 and R3 tags in the template with the corresponding SMILES from the R2 and R3 lists, and then writing out the resulting molecules to an SDF file and a CSV file.
# SDFs are created with each permutation with a new ligand ID created for each unique permutation of systematic mods
def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--r2_tsv", required=True)
    ap.add_argument("--r3_tsv", required=True)
    ap.add_argument("--out_sdf", required=True)
    ap.add_argument("--out_smiles", required=True)
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--name_prefix", default="emap3_")
    ap.add_argument("--expect", type=int, default=2040)
    args=ap.parse_args()

    r2_list=load_tsv(args.r2_tsv)   
    r3_list=load_tsv(args.r3_tsv)    
    target=len(r2_list)*len(r3_list)

    os.makedirs(os.path.dirname(args.out_sdf), exist_ok=True)

    writer=Chem.SDWriter(args.out_sdf)
    rows=[]; ok=fail=0; bad=[]
    for r2n,r2 in r2_list:
        for r3n,r3 in r3_list:
            name=f"{args.name_prefix}{r2n}_{r3n}"
            smi=TEMPLATE.replace("{R2}",r2).replace("{R3}",r3)
            mol=Chem.MolFromSmiles(smi)
            if mol is None:
                fail+=1; bad.append((name,smi,"MolFromSmiles failed")); continue
            try:
                Chem.SanitizeMol(mol)
            except Exception as e:
                fail+=1; bad.append((name,smi,f"SanitizeMol: {e}")); continue
            try:
                AllChem.EmbedMolecule(mol, randomSeed=17)
                AllChem.UFFOptimizeMolecule(mol, maxIters=200)
            except Exception:
                pass
            mol.SetProp("_Name", name)
            writer.write(mol)
            rows.append((name,smi))
            ok+=1
    writer.close()

    with open(args.out_smiles,"w",newline="") as f:
        cw=csv.writer(f); cw.writerow(["ligand_id","smiles"]); cw.writerows(rows)

# manifest created - total ligands - passed ligands are deposited into the failed CSV for future analysis, manifest value created
# analogous to R snippet with args.manifest command, AI was used for this snippet - ChatGPT, OpenAI, 5.2 version, 2025
    with open(args.manifest,"w") as f:
        f.write("Round-3 enumeration manifest\n")
        f.write("Created: 2025-10-28\n")
        f.write(f"R2_tsv: {args.r2_tsv}\nR3_tsv: {args.r3_tsv}\n")
        f.write(f"SDF: {args.out_sdf}\nCSV: {args.out_smiles}\n")
        f.write(f"Total intended (|R2|*|R3|): {target}\n")
        f.write(f"Wrote: {ok}\nFailed: {fail}\n")
        try: f.write(f"SDF sha256: {sha256(args.out_sdf)}\n")
        except: pass
        try: f.write(f"CSV sha256: {sha256(args.out_smiles)}\n")
        except: pass
        f.write("\nUnique R2 tags:\n")
        f.write(", ".join([t for t,_ in r2_list])+"\n")
        f.write("\nUnique R3 tags:\n")
        f.write(", ".join([t for t,_ in r3_list])+"\n")
        if bad:
            f.write("\nFailures (first 50):\n")
            for b in bad[:50]:
                f.write(f"{b[0]}\t{b[1]}\t{b[2]}\n")

    # hard validation
    if ok != target:
        print(f"[ERROR] Wrote {ok}, expected {target}. See manifest {args.manifest}.", file=sys.stderr)
        sys.exit(1)
    if args.expect and ok != args.expect:
        print(f"[ERROR] Wrote {ok}, expected --expect {args.expect}.", file=sys.stderr)
        sys.exit(1)

    print(f"[enumeration] wrote {ok} / expected {target} → {args.out_sdf}")
    print(f"[enumeration] SMILES → {args.out_smiles}")
    print(f"[enumeration] manifest → {args.manifest}")

if __name__=="__main__":
    main()
